blank_issues_enabled: false
contact_links:
  - name: 'ğŸ“ Documentation'
    url: https://github.com/cloudskiff/driftctl-docs/issues/new
    about: Please open documentation issue on driftctl docs repository
  - name: 'ğŸ‘¾ Support chat'
    url: https://discord.gg/NMCBxtD7Nd
    about: Find support with community chat on discord
